export const IS_SEARCHING = 'IS_SEARCHING';
export const SEARCHES_RECEIVED = 'SEARCHES_RECEIVED';

export const PLAYLIST_RECEIVED = 'PLAYLIST_RECEIVED';
export const PLAYLIST_IS_FETCHING = 'PLAYLIST_RECEIVED';
export const PLAYLIST_SONG_ADDED = 'PLAYLIST_SONG_ADDED';
export const PLAYLIST_SONG_REMOVED = 'PLAYLIST_SONG_ADDED';
export const PLAYLIST_UPDATED = 'PLAYLIST_UPDATED';
export const PLAYLIST_CLEARED = 'PLAYLIST_CLEARED';

export const PLAYER_PAUSED = 'PLAYER_PAUSED';
export const PLAYER_PLAYED = 'PLAYER_PLAYED';
export const PLAYER_FAST_FORWARD = 'PLAYER_PLAYED';
export const PLAYER_SONG_FINISHED = 'PLAYER_SONG_FINISHED';
